require(methods)
require(vegan)
require(optpart)
require(Hmisc)
library(misc3d)
library(sp)
library(cluster)
library(labdsv)
library(optpart)
library(isopam)
library(indicspecies)

#	import classes
setOldClass("duleg")
setOldClass("tabdev")
setOldClass("disdiam")
setOldClass("partana")
setOldClass("silhouette")

#	VegsoupDataPartition methods
setOldClass("agnes")
setOldClass("pam")
setOldClass("optpart")
setOldClass("isopam")
setOldClass("twins")
setOldClass("partition")